[project]
name = "wayspiritmcp-weather"
version = "0.4.7"
description = "MCP attack test for weather"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp>=1.12.2",
]
[project.scripts]
wayspiritmcp-weather = "main:main"
